[MapVote.Sound]
SoundFile = "soundevents/test.vsndevts"
InitialVoteCountdownStartSound = "initial_countdown_start"
InitialVoteStartSound = "initial_start"
InitialVoteFinishSound = "initial_finish"
InitialVoteCountdownSound1 = "tick1"
InitialVoteCountdownSound2 = "tick2"
InitialVoteCountdownSound3 = "tick3"
InitialVoteCountdownSound4 = ""
InitialVoteCountdownSound5 = ""
InitialVoteCountdownSound6 = ""
InitialVoteCountdownSound7 = ""
InitialVoteCountdownSound8 = ""
InitialVoteCountdownSound9 = ""
InitialVoteCountdownSound10 = "tick10"
RunoffVoteCountdownStartSound = "runoff_countdown_start"
RunoffVoteStartSound = "runoff_start"
RunoffVoteFinishSound = "runoff_finish"
RunoffVoteCountdownSound1 = "rtick1"
RunoffVoteCountdownSound2 = ""
RunoffVoteCountdownSound3 = ""
RunoffVoteCountdownSound4 = ""
RunoffVoteCountdownSound5 = ""
RunoffVoteCountdownSound6 = ""
RunoffVoteCountdownSound7 = ""
RunoffVoteCountdownSound8 = ""
RunoffVoteCountdownSound9 = ""
RunoffVoteCountdownSound10 = "rtick10"
