[MapChooserSharpSettings.Default]
MinPlayers = 0

[MapChooserSharpSettings.Groups.G1]
MaxPlayers = 1000

[MapChooserSharpSettings.Groups.G2]
MinPlayers = 300

[MapChooserSharpSettings.Groups.G3]
MapTime = 40

[ze_multi_group]
GroupSettings = ["G1", "G2", "G3"]
