[MapChooserSharpSettings.Default]
MaxExtends = 3

[ze_force]
MaxExtends = 4

[ze_force.DaySettings.LowPriority]
Enabled = true
ForceOverride = true
OverridePriority = 1
TargetDays = ["saturday"]
MaxExtends = 6

[ze_force.DaySettings.HighPriority]
Enabled = true
ForceOverride = true
OverridePriority = 5
TargetDays = ["sunday"]
MaxExtends = 10
