[MapChooserSharpSettings.Default]
MaxExtends = 1

[MapChooserSharpSettings.Groups.Group1]
MaxPlayers = 1000

[MapChooserSharpSettings.Groups.Group2]
MinPlayers = 300

[ze_test]
GroupSettings = ["Group1", "Group2"]
