[MapChooserSharpSettings.Default]
MaxExtends = 3

[MapChooserSharpSettings.Groups.G1]
MaxExtends = 5

[MapChooserSharpSettings.Groups.G1.DaySettings.EventDay]
Enabled = true
TargetDays = ["saturday"]
MaxExtends = 10

[ze_test]
GroupSettings = ["G1"]
