[MapChooserSharpSettings.Default]
MaxExtends = 3
MinPlayers = 5

[MapChooserSharpSettings.Groups.G1]
MaxExtends = 5

[MapChooserSharpSettings.Groups.G1.DaySettings.EventDay]
Enabled = true
TargetDays = ["saturday"]
MinPlayers = 30

[ze_test]
GroupSettings = ["G1"]
MapTime = 45
