[MapChooserSharpSettings.Default]
MaxExtends = 3

[MapChooserSharpSettings.Groups.G1]
RequiredPermissions = ["mcs.nominate.management"]

[MapChooserSharpSettings.Groups.G2]
RequiredPermissions = ["mcs.nominate.generic"]

[ze_test]
GroupSettings = ["G1", "G2"]
