[MapChooserSharpSettings.Default]
RequiredPermissions = ["mcs.nominate.default"]
AllowedSteamIds = [100]
DisallowedSteamIds = [200]

[MapChooserSharpSettings.Groups.G1]
RequiredPermissions = ["mcs.nominate.management"]
AllowedSteamIds = [111]
DisallowedSteamIds = [222]

[ze_test]
GroupSettings = ["G1"]
RequiredPermissions = ["mcs.nominate.map.vip"]
AllowedSteamIds = [333]
DisallowedSteamIds = [444]
