[MapChooserSharpSettings.Default]
Cooldown = 10

[MapChooserSharpSettings.Groups.G1]
Cooldown = 20

[MapChooserSharpSettings.Groups.G1.DaySettings.Weekend]
Enabled = true
TargetDays = ["saturday"]
Cooldown = 25

[ze_test]
GroupSettings = ["G1"]
Cooldown = 30

[ze_test.DaySettings.Special]
Enabled = true
TargetDays = ["sunday"]
Cooldown = 35
